<a href="https://colab.research.google.com/github/dubuel/MLPytorch/blob/main/dubuel./numpytutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [108]:
import numpy as np

In [ ]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a = np.append(a, 4)

In [ ]:
print(a)

[1 2 3 4]


In [ ]:
b = np.append(a,5)

In [ ]:
print(a,b)

[1 2 3 4] [1 2 3 4 5]


In [ ]:
a = np.random.rand(2,2)
print(a)

[[0.94300673 0.20369791]
 [0.69290421 0.29672031]]


In [ ]:
b = np.random.randn(2,2)
print(b)

[[ 0.53896373 -0.86871124]
 [-0.73120675 -0.07453256]]


In [ ]:
b = np.arange(1,13)
print(b)
print(b.shape)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1


In [ ]:
b = b.reshape(3,-1)
print(b)
print(b.shape)
print(b.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [ ]:
row_r1 = b[1,:]
row_r2 = b[1:2,:]
print(row_r1, row_r1.shape, row_r1.ndim)
print(row_r2, row_r2.shape, row_r2.ndim)

[5 6 7 8] (4,) 1
[[5 6 7 8]] (1, 4) 2


In [ ]:
c = np.arange(24).reshape(2,3,-1)
print(c)
print(c.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [ ]:
print(c[:,:,:1])
print(c[...,:1])

[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]
[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]


In [ ]:
print(c[0:1,2])

[[ 8  9 10 11]]


In [ ]:
bool_idx = (c>10)
print(bool_idx)

[[[False False False False]
  [False False False False]
  [False False False  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [ ]:
c[c>10] = -3
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 -3]]

 [[-3 -3 -3 -3]
  [-3 -3 -3 -3]
  [-3 -3 -3 -3]]]


In [ ]:
d = np.arange(24).reshape(4,3,-1)
h = np.arange(6).reshape(6,-1)
print(d, d.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]] (4, 3, 2)


In [ ]:
d = np.hstack((d,d,d,d))
print(d, d.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 0  1]
  [ 2  3]
  [ 4  5]
  [ 0  1]
  [ 2  3]
  [ 4  5]
  [ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]
  [ 6  7]
  [ 8  9]
  [10 11]
  [ 6  7]
  [ 8  9]
  [10 11]
  [ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]
  [12 13]
  [14 15]
  [16 17]
  [12 13]
  [14 15]
  [16 17]
  [12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]
  [18 19]
  [20 21]
  [22 23]
  [18 19]
  [20 21]
  [22 23]
  [18 19]
  [20 21]
  [22 23]]] (4, 12, 2)


In [ ]:
print(d[[3,2,1,0]])

[[[18 19]
  [20 21]
  [22 23]
  [18 19]
  [20 21]
  [22 23]
  [18 19]
  [20 21]
  [22 23]
  [18 19]
  [20 21]
  [22 23]]

 [[12 13]
  [14 15]
  [16 17]
  [12 13]
  [14 15]
  [16 17]
  [12 13]
  [14 15]
  [16 17]
  [12 13]
  [14 15]
  [16 17]]

 [[ 6  7]
  [ 8  9]
  [10 11]
  [ 6  7]
  [ 8  9]
  [10 11]
  [ 6  7]
  [ 8  9]
  [10 11]
  [ 6  7]
  [ 8  9]
  [10 11]]

 [[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 0  1]
  [ 2  3]
  [ 4  5]
  [ 0  1]
  [ 2  3]
  [ 4  5]
  [ 0  1]
  [ 2  3]
  [ 4  5]]]


In [97]:
e = np.arange(32).reshape(8,4)
print(e, e.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] (8, 4)


In [103]:
print(e[[1,5,7,2]])

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]


In [107]:
print(e[[1],[1]])

[5]


In [ ]:
print(e[[1,5,7,2]][:, [0,3,1,2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [ ]:
f = np.arange(16).reshape(4,4)
print(f, f.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] (4, 4)


In [ ]:
print(f.transpose(1,0))

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [112]:
z = np.arange(1,11).reshape(2,-1)
print(z, z.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5)


In [111]:
sum1 = np.sum(z, axis = 0)
sum2 = np.sum(z, axis =1)
print(sum1)
print(sum2)

[ 7  9 11 13 15]
[15 40]


Broadcasting

In [113]:
x = np.array([1,2,3]).reshape(1,3)
y = np.array([4,5]).reshape(1,2)
print(x, x.shape)
print(y, y.shape)

[[1 2 3]] (1, 3)
[[4 5]] (1, 2)


In [ ]:
print(x+y)

In [116]:
y = y.transpose(1,0)
print(y, y.shape)

[[4]
 [5]] (2, 1)


In [117]:
print(x+y) 

[[5 6 7]
 [6 7 8]]


Shape 변경

In [119]:
a = np.arange(24).reshape(2,3,4)
print(a, a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4)


In [132]:
a = np.reshape(a,(4,-1))
print(a, a.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] (4, 6)


In [133]:
a = a[...,np.newaxis]
print(a, a.shape)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]
  [16]
  [17]]

 [[18]
  [19]
  [20]
  [21]
  [22]
  [23]]] (4, 6, 1)


In [ ]:
a = np.reshape(a,(4,6,1))
print(a, a.shape)

In [136]:
a = np.reshape(a,(4,-1))
a = np.expand_dims(a, axis=1)
print(a, a.shape)

[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]]

 [[18 19 20 21 22 23]]] (4, 1, 6)


In [152]:
b = a.copy()
print(b, b.shape)

[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]]

 [[18 19 20 21 22 23]]] (4, 1, 6)


In [151]:
c = np.concatenate((a,b), axis= 1)
print(c, c.shape)

[[[ 0  1  2  3  4  5]
  [ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [18 19 20 21 22 23]]] (4, 2, 6)


In [142]:
c = np.concatenate((a,b), axis= 0)
print(c, c.shape)

[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]]

 [[18 19 20 21 22 23]]

 [[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]] (6, 1, 6)


In [148]:
d = np.stack((a,b), axis = 0)
print(d, d.shape)

[[[[ 0  1  2  3  4  5]]

  [[ 6  7  8  9 10 11]]

  [[12 13 14 15 16 17]]

  [[18 19 20 21 22 23]]]


 [[[ 0  1  2  3  4  5]]

  [[ 6  7  8  9 10 11]]

  [[12 13 14 15 16 17]]

  [[18 19 20 21 22 23]]]] (2, 4, 1, 6)


In [149]:
d = np.stack((a,b), axis = -1)
print(d, d.shape)

[[[[ 0  0]
   [ 1  1]
   [ 2  2]
   [ 3  3]
   [ 4  4]
   [ 5  5]]]


 [[[ 6  6]
   [ 7  7]
   [ 8  8]
   [ 9  9]
   [10 10]
   [11 11]]]


 [[[12 12]
   [13 13]
   [14 14]
   [15 15]
   [16 16]
   [17 17]]]


 [[[18 18]
   [19 19]
   [20 20]
   [21 21]
   [22 22]
   [23 23]]]] (4, 1, 6, 2)


In [150]:
d = np.stack((a,b), axis = 1)
print(d, d.shape)

[[[[ 0  1  2  3  4  5]]

  [[ 0  1  2  3  4  5]]]


 [[[ 6  7  8  9 10 11]]

  [[ 6  7  8  9 10 11]]]


 [[[12 13 14 15 16 17]]

  [[12 13 14 15 16 17]]]


 [[[18 19 20 21 22 23]]

  [[18 19 20 21 22 23]]]] (4, 2, 1, 6)
