<a href="https://colab.research.google.com/github/dubuel/MLPytorch/blob/main/dubuel./tensor_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
from tensorflow import keras

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
mnist = keras.datasets.mnist

(x_train, y_train) , (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train /255.0, x_test/ 255.0

In [ ]:
hello = tf.constant([3,3],dtype = tf.float64)
print(hello)

tf.Tensor([3. 3.], shape=(2,), dtype=float64)


In [ ]:
#tf.constant를 활용하여 상수형 tensor 생성가능

In [ ]:
x = tf.constant(([1,2],[3,4]))
print(x)
print(type(x))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
a = tf.ones((3,3))
b = tf.zeros((2,3))
c = tf.fill((2,3),2)
print(a)
print(b)
print(c)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2 2 2]
 [2 2 2]], shape=(2, 3), dtype=int32)


In [ ]:
d = tf.zeros_like(c)
e = tf.ones_like(c)
print(d)
print(e)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [ ]:
f = tf.eye(3)
print(f)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
g = tf.range(10)
print(g)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [ ]:
h = tf.random.uniform((2,2)) #np.rand
i = tf.random.normal((2,2)) #np.randn
print(h)
print(i)

tf.Tensor(
[[0.6119149  0.59872353]
 [0.74145436 0.92799723]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.21650255  0.06280637]
 [ 1.7444043   0.09064346]], shape=(2, 2), dtype=float32)


In [ ]:
tensor = tf.random.normal((3,4))

In [ ]:
print(tensor.shape)
print(tensor.dtype)
print(tensor)

(3, 4)
<dtype: 'float32'>
tf.Tensor(
[[ 0.41460854 -1.0526108   1.006817    0.89333415]
 [ 0.48988506 -0.45917648  0.57938373 -1.0706774 ]
 [-0.61442155  0.1148587   0.425296   -0.41453618]], shape=(3, 4), dtype=float32)


In [ ]:
tensor = tf.reshape(tensor,(4,3))
tensor = tf.cast(tensor,tf.int32)
print(tensor)

tf.Tensor(
[[ 0 -1  1]
 [ 0  0  0]
 [ 0 -1  0]
 [ 0  0  0]], shape=(4, 3), dtype=int32)


In [ ]:
tensor = tf.ones((3,3))
print(tensor)

NameError: ignored

In [ ]:
variable = tf.Variable(tensor)
print(variable)

variable[0,0].assign(2)
print(variable)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[2., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>


In [5]:
z = tf.range(1,11)
z = tf.reshape(z,(2,5))
print(z)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)


In [9]:
print(tf.reduce_sum(z))

tf.Tensor(55, shape=(), dtype=int32)


In [13]:
print(tf.reduce_sum(z, axis=0))
print(tf.reduce_sum(z, axis=1))
print(tf.reduce_sum(z, axis=-1))

tf.Tensor([ 7  9 11 13 15], shape=(5,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)
tf.Tensor([15 40], shape=(2,), dtype=int32)
