# Numpy Basic

In [51]:
import numpy as np

## data type

array의 dtype을 본다. 

In [52]:
arr = np.array([[1., 2, 3], [1, 2, 3]])

In [53]:
arr.dtype

dtype('float64')

.astype()으로 datatype을 변환 가능

In [54]:
arr = arr.astype(np.int32)

In [55]:
arr.dtype

dtype('int32')

len(arr.shape) 를 통해서 차원의 갯수를 확인 할 수 있지만,  
아래와 같이 ndim을 통해 차원 수를 return 가능

In [56]:
len(arr.shape)

2

In [57]:
np.ndim(arr)

2

In [58]:
arr.shape

(2, 3)

size 확인

In [59]:
arr.size

6

dtype 확인

In [60]:
arr.dtype

dtype('int32')

## Reshape

In [61]:
arr.shape

(2, 3)

Reshape 

In [62]:
arr.reshape(1,6)

array([[1, 2, 3, 1, 2, 3]])

In [63]:
arr = np.array([[1,2,3], [1,2,3]])

In [64]:
arr.reshape([6]).shape

(6,)

Reshape, -1 활용

In [65]:
arr = arr.reshape(-1)
arr.shape

(6,)

In [66]:
arr = arr.reshape(-1, 3) # 총 6개의 원소가 있었으므로, -1 => 6/3 = 2 배정
arr.shape

(2, 3)

random array 생성

In [67]:
arr = np.random.randn(8, 8) # random normal distribution
arr.shape

(8, 8)

In [68]:
arr = arr.reshape(32,2) # list 넣든, tuple 넣든 상관 없는듯
arr.shape

(32, 2)

In [69]:
arr = arr.reshape([32, 2])
arr.shape

(32, 2)

3차원으로 늘리기

In [70]:
arr.shape

(32, 2)

In [71]:
arr = arr.reshape(-1, 2, 1, 1, 1, 1)
arr.shape

(32, 2, 1, 1, 1, 1)

## Ravel

In [72]:
arr.shape

(32, 2, 1, 1, 1, 1)

In [73]:
arr = arr.ravel()
arr.shape

(64,)

arr의 차원을 1로 바꿔줌  
나중에 배울 layer를 flatten 할 때 같은 기능이라 생각하면 됨 

arr.reshape(-1) 와 같음

In [74]:
arr.ravel() == arr.reshape(-1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## np.expand_dims()

안의 값은 유지하되 차원 수를 늘리고 싶을 때가 있음  
이럴 때 사용하는 것이 expand_dims  

In [75]:
arr.shape

(64,)

In [76]:
arr = np.expand_dims(arr, -1)
arr. shape

(64, 1)

In [77]:
arr = arr.ravel()

In [78]:
arr.shape

(64,)

In [79]:
arr = np.expand_dims( np.expand_dims(arr,-1), 0)

In [80]:
arr.shape

(1, 64, 1)

## zeros & ones

0으로 채워진 numpy array를 만들 수 있음

In [81]:
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [82]:
zeros = np.zeros(1)
zeros

array([0.])

In [83]:
ones = np.ones([10,5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
ones*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [85]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [86]:
arr = np.arange(4,9)
arr

array([4, 5, 6, 7, 8])

In [87]:
arr = np.arange(10, 20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [88]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Index

In [89]:
nums = [1,2,3,4,5]

In [90]:
nums[2:]

[3, 4, 5]

In [91]:
nums = [1, 2, 3, 4, [1, 2, 3]]
nums

[1, 2, 3, 4, [1, 2, 3]]

In [92]:
nums[4]

[1, 2, 3]

In [93]:
arr[1][2]

5

In [94]:
arr[1,2]

5

# Slicing

In [95]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [97]:
arr[1:, 1:]

array([[4, 5],
       [7, 8]])

In [98]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Boolean Indexing

In [99]:
data = np.random.randn(3, 3)
data

array([[-1.05488711,  1.43601084,  0.40738287],
       [-1.62209477, -1.75207968,  1.40546721],
       [-1.31800083,  0.75664882,  0.28981451]])

In [100]:
data <= 0

array([[ True, False, False],
       [ True,  True, False],
       [ True, False, False]])

In [101]:
data [data <= 0] = 1

In [102]:
data

array([[1.        , 1.43601084, 0.40738287],
       [1.        , 1.        , 1.40546721],
       [1.        , 0.75664882, 0.28981451]])

# Broadcast

tensorflow나 pytorch로 계산하면 broadcast의 개념도 잘 이해해야 함

broadcast는 연산 하려는 서로 다른 두개의 행렬의 shape가 같지 않고,  
한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일 때  
이를 여러 복사를 하여 연산을 함

In [103]:
import numpy as np

In [104]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [105]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [106]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [107]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [108]:
arr + np.array([1,2,3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

## Math Function

In [109]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [110]:
arr * 5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [111]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [112]:
np.add(arr, 1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
arr + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
np.multiply(arr, 3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [120]:
arr = np.random.randint(2, size=27).reshape(3, 3, 3)
arr

array([[[0, 1, 1],
        [1, 1, 0],
        [0, 1, 1]],

       [[1, 1, 0],
        [1, 1, 0],
        [0, 1, 1]],

       [[1, 0, 0],
        [0, 1, 1],
        [0, 0, 0]]])

In [123]:
arr_2 = np.random.randint(2, size=9).reshape(3,3)

In [124]:
arr_2

array([[1, 1, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [125]:
arr.shape, arr_2.shape

((3, 3, 3), (3, 3))

In [126]:
arr + arr_2

array([[[1, 2, 1],
        [2, 1, 0],
        [0, 1, 1]],

       [[2, 2, 0],
        [2, 1, 0],
        [0, 1, 1]],

       [[2, 1, 0],
        [1, 1, 1],
        [0, 0, 0]]])

In [127]:
arr * arr_2

array([[[0, 1, 0],
        [1, 0, 0],
        [0, 0, 0]],

       [[1, 1, 0],
        [1, 0, 0],
        [0, 0, 0]],

       [[1, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [128]:
np.array([[1,2],[3,4]]) * np.eye(2)

array([[1., 0.],
       [0., 4.]])

In [129]:
np.sum(arr)

15

In [130]:
np.sum(arr+arr_2)

24

In [131]:
arr + arr_2

array([[[1, 2, 1],
        [2, 1, 0],
        [0, 1, 1]],

       [[2, 2, 0],
        [2, 1, 0],
        [0, 1, 1]],

       [[2, 1, 0],
        [1, 1, 1],
        [0, 0, 0]]])

In [132]:
np.max(arr+arr_2)

2

In [133]:
np.min(arr+arr_2)

0

In [134]:
np.max(arr + arr_2, -1)

array([[2, 2, 1],
       [2, 2, 1],
       [2, 1, 0]])

In [135]:
arr_3 = np.arange(9).reshape(3,3)
np.max(arr_3,-1)

array([2, 5, 8])

In [136]:
np.sum( arr + arr_2, axis=-1)

array([[4, 3, 2],
       [4, 3, 2],
       [3, 3, 0]])

In [137]:
np.mean(arr)

0.5555555555555556

In [139]:
arr = np.array([1, 6, 3, 7, 3, 2, 9, 0, 2])
arr

array([1, 6, 3, 7, 3, 2, 9, 0, 2])

In [140]:
np.argmax(arr)

6

In [141]:
np.argmin(arr)

7

In [142]:
arr = np.array([3, 5, 6, 6, 3, 3, 1])

In [143]:
np. unique(arr)

array([1, 3, 5, 6])